### ISSUE TITLE
Compiling Assets

### ISSUE THREAD

**Issue by mikeydiamonds** [Dev7studios/chip#18]
It appears the files in `vendor/dev7studios/chip/src/js/components` have no bearing on customizing the app. The only file that actually makes changes is `vendor/dev7studios/chip/dist/chip.js`. Does anyone know how to fix this and make the non-compiled files useful? I'm not familiar enough with laravel mix to make it work.

**Comment by gilbitron** [comment]
If you run `php artisan vendor:publish --tag=chip-components` this will make the individual components available in `resources/assets/js/vendor/chip`. You can then customize and use the individual components in your app. See [this doc](https://chipbilling.com/docs/vue-components) for more info.

**Comment by mikeydiamonds** [comment]
Thanks for the reply @gilbitron. I did publish the components, I'm just not sure how to properly "wire" them back up to use the published assets instead of the original `chip.js` file. Sorry, I'm very new to this.

**Comment by mikeydiamonds** [comment]
I just added `Vue.component('billing', require('./../../../vendor/dev7studios/chip/src/laravel/resources/assets/js/components/Billing.vue'));` to my `app.js` file and now things are working. I know that's ugly but it's working for now. Thanks for the clues in your docs. Leaving my rambling here to help others.
